<?php
/*
 * The 100 questions. Heart #1 is the first entry, heart #100 the last.
 *
 *   ['type' => 'choice', 'q' => 'Question?', 'options' => ['A', 'B', 'C', 'D']]
 *   ['type' => 'open',   'q' => 'Question answered in the chat']
 *
 * "Me" / "You" options are from the point of view of whoever is answering.
 * Edit freely — the game shows as many hearts as there are questions.
 */
return [
    /* 1 */ ['type' => 'choice', 'q' => 'What was your very first impression of me?', 'options' => ['Cute, instantly', 'Mysterious', 'Funny', "Honestly? I didn't notice at first 😅"]],
    /* 2 */ ['type' => 'open',   'q' => 'Describe the moment you realized you had feelings for me.'],
    /* 3 */ ['type' => 'choice', 'q' => 'Our perfect date night is…', 'options' => ['A cozy movie at home', 'A fancy dinner out', 'A long walk and talk', 'A spontaneous adventure']],
    /* 4 */ ['type' => 'choice', 'q' => 'Which little thing about me is secretly your favorite?', 'options' => ['The way I laugh', 'How I text you', 'How I look at you', 'My terrible jokes']],
    /* 5 */ ['type' => 'open',   'q' => 'What is one thing I do that always makes you feel loved?'],
    /* 6 */ ['type' => 'choice', 'q' => 'If we could teleport anywhere together right now, where?', 'options' => ['A beach at sunset', 'A snowy mountain cabin', 'A big buzzing city', 'Back to our first date spot']],
    /* 7 */ ['type' => 'choice', 'q' => 'Who says sorry first after an argument?', 'options' => ['Me', 'You', 'Whoever gets hungry first 😂', 'We both say it at the same time']],
    /* 8 */ ['type' => 'open',   'q' => 'What is your favorite memory of us so far?'],
    /* 9 */ ['type' => 'choice', 'q' => 'What is your main love language?', 'options' => ['Words of affirmation', 'Quality time', 'Physical touch', 'Acts of service', 'Gifts']],
    /* 10 */ ['type' => 'choice', 'q' => 'Pick our couple superpower:', 'options' => ["Reading each other's minds", 'Teleporting to each other', 'Pausing time together', 'Never running out of things to say']],
    /* 11 */ ['type' => 'open',   'q' => 'Which song reminds you of us, and why?'],
    /* 12 */ ['type' => 'choice', 'q' => 'Who is more likely to fall asleep during a movie?', 'options' => ['Me', 'You', 'Both, obviously', 'Neither — we talk the whole time']],
    /* 13 */ ['type' => 'choice', 'q' => 'Breakfast in bed: what is on the tray?', 'options' => ['Pancakes & honey', 'Omelette & toast', 'Fruit & coffee', 'Croissants & juice']],
    /* 14 */ ['type' => 'open',   'q' => "What is a dream you've never told anyone — but want to tell me?"],
    /* 15 */ ['type' => 'choice', 'q' => 'How do you like to be comforted when you are sad?', 'options' => ['Just hold me, no words', 'Talk it through with me', 'Make me laugh', 'Give me space, then come back']],
    /* 16 */ ['type' => 'choice', 'q' => 'Our dream home must have…', 'options' => ['A big kitchen', 'A garden', 'A cozy reading corner', 'A view of the water']],
    /* 17 */ ['type' => 'open',   'q' => 'Give me three words that describe me — and explain one of them.'],
    /* 18 */ ['type' => 'choice', 'q' => 'Which would you rather receive from me?', 'options' => ['A handwritten letter', 'A surprise visit', 'A playlist made for you', "A random 'I miss you' call"]],
    /* 19 */ ['type' => 'choice', 'q' => 'Who is the better cook?', 'options' => ['Me', 'You', "It's a tie", "Let's just order food 😅"]],
    /* 20 */ ['type' => 'open',   'q' => 'What do you think our life looks like in five years?'],
    /* 21 */ ['type' => 'choice', 'q' => 'Favorite time of day to spend together?', 'options' => ['Early morning', 'Lazy afternoon', 'Sunset', 'Late at night']],
    /* 22 */ ['type' => 'choice', 'q' => 'If our story were a movie, the genre would be…', 'options' => ['Romantic comedy', 'Adventure', 'Drama', 'Musical']],
    /* 23 */ ['type' => 'open',   'q' => 'What is something small I did that meant a lot to you?'],
    /* 24 */ ['type' => 'choice', 'q' => 'Who is more jealous?', 'options' => ['Me', 'You', 'Both, a little', 'Neither — we trust 100%']],
    /* 25 */ ['type' => 'choice', 'q' => 'Pick our weekend away:', 'options' => ['Road trip', 'Staycation with snacks', 'Hike & picnic', 'Visiting family']],
    /* 26 */ ['type' => 'open',   'q' => 'When do you feel closest to me?'],
    /* 27 */ ['type' => 'choice', 'q' => 'What do I do that makes you laugh the most?', 'options' => ['My faces', 'My jokes', 'My dancing', 'When I try to be serious']],
    /* 28 */ ['type' => 'choice', 'q' => 'Which pet would we raise together?', 'options' => ['A dog', 'A cat', 'A parrot', "Plants only, let's be honest"]],
    /* 29 */ ['type' => 'open',   'q' => 'What is one thing you want us to try together for the first time?'],
    /* 30 */ ['type' => 'choice', 'q' => "Who usually texts 'good morning' first?", 'options' => ['Me', 'You', 'Whoever wakes up first', 'We send it at the same time']],
    /* 31 */ ['type' => 'choice', 'q' => 'How should we celebrate our next anniversary?', 'options' => ['A trip', 'Dinner somewhere new', 'Recreate our first date', 'A quiet day, just us']],
    /* 32 */ ['type' => 'open',   'q' => 'What do you admire most about me?'],
    /* 33 */ ['type' => 'choice', 'q' => 'The best kind of gift is…', 'options' => ['Something handmade', 'An experience together', 'Something I mentioned once', 'A total surprise']],
    /* 34 */ ['type' => 'choice', 'q' => 'What is my most attractive quality to you?', 'options' => ['My smile', 'My eyes', 'My kindness', 'My mind']],
    /* 35 */ ['type' => 'open',   'q' => 'Describe your perfect lazy Sunday with me, from morning to night.'],
    /* 36 */ ['type' => 'choice', 'q' => 'In a zombie apocalypse, who survives longer?', 'options' => ['Me', 'You', 'We survive together', 'Neither of us 😂']],
    /* 37 */ ['type' => 'choice', 'q' => 'Which is the most romantic?', 'options' => ['Dancing in the kitchen', 'Stargazing', 'Candlelight dinner', 'A walk in the rain']],
    /* 38 */ ['type' => 'open',   'q' => 'What is a fear you have about love, and how can I help with it?'],
    /* 39 */ ['type' => 'choice', 'q' => 'Who is the bigger romantic?', 'options' => ['Me', 'You', 'Equal', 'Depends on the day']],
    /* 40 */ ['type' => 'choice', 'q' => 'If we opened a small business together, it would be…', 'options' => ['A café', 'A bakery', 'A travel agency', 'A flower shop']],
    /* 41 */ ['type' => 'open',   'q' => 'What is one promise you want to make to me today?'],
    /* 42 */ ['type' => 'choice', 'q' => "Favorite way to say 'I love you' without words?", 'options' => ['A long hug', 'A forehead kiss', 'Holding hands', 'A look across the room']],
    /* 43 */ ['type' => 'choice', 'q' => 'What do we (playfully) argue about the most?', 'options' => ['Food', 'What to watch', "Who's right", 'Who loves who more']],
    /* 44 */ ['type' => 'open',   'q' => 'What did you think the very first time we talked?'],
    /* 45 */ ['type' => 'choice', 'q' => 'Who remembers important dates better?', 'options' => ['Me', 'You', 'Our phones do', 'Neither 🙈']],
    /* 46 */ ['type' => 'choice', 'q' => 'Dream honeymoon?', 'options' => ['Beach', 'Mountains', 'A city trip', 'All of the above']],
    /* 47 */ ['type' => 'open',   'q' => 'What is the most beautiful thing about our relationship?'],
    /* 48 */ ['type' => 'choice', 'q' => 'Which emoji do I send you the most?', 'options' => ['❤️', '😂', '🥺', '😘']],
    /* 49 */ ['type' => 'choice', 'q' => 'Describe our love in one word:', 'options' => ['Sweet', 'Wild', 'Safe', 'Magical']],
    /* 50 */ ['type' => 'open',   'q' => 'If you could relive one day with me, which one and why?'],
    /* 51 */ ['type' => 'choice', 'q' => 'Who would win a dance battle?', 'options' => ['Me', 'You', "Nobody — we'd be laughing too hard", "Let's find out tonight"]],
    /* 52 */ ['type' => 'choice', 'q' => 'What should we learn together?', 'options' => ['A new language', 'Cooking', 'Dancing', 'Photography']],
    /* 53 */ ['type' => 'open',   'q' => 'What is something you want me to know but find hard to say?'],
    /* 54 */ ['type' => 'choice', 'q' => 'Who is more stubborn?', 'options' => ['Me', 'You', 'Equally 😅', "We're both perfect angels"]],
    /* 55 */ ['type' => 'choice', 'q' => 'Rainy day plan?', 'options' => ['Blanket + movies', 'Cook something warm', 'Talk for hours', 'Sleep in']],
    /* 56 */ ['type' => 'open',   'q' => 'How do you want us to handle hard times together?'],
    /* 57 */ ['type' => 'choice', 'q' => 'What is cutest about me when I am sleepy?', 'options' => ['My voice', 'My face', 'How clingy I get', 'The random things I say']],
    /* 58 */ ['type' => 'choice', 'q' => 'Who would plan our dream wedding better?', 'options' => ['Me', 'You', 'Together', "We'd elope 😂"]],
    /* 59 */ ['type' => 'open',   'q' => "Write me a tiny love note — as if I'll find it in my pocket tomorrow."],
    /* 60 */ ['type' => 'choice', 'q' => 'Favorite kind of photo of us?', 'options' => ['Selfies', 'Candid moments', 'Mirror pictures', 'Silly faces']],
    /* 61 */ ['type' => 'choice', 'q' => 'Which chore would you take forever so I never have to?', 'options' => ['Dishes', 'Laundry', 'Cooking', 'Grocery shopping']],
    /* 62 */ ['type' => 'open',   'q' => 'What is one thing about your childhood you want me to understand?'],
    /* 63 */ ['type' => 'choice', 'q' => 'If I were a food, I would be…', 'options' => ['Chocolate — sweet', 'Pepper — spicy', 'Fresh bread — comforting', 'Ice cream — cool']],
    /* 64 */ ['type' => 'choice', 'q' => 'Where do you see us living one day?', 'options' => ['In the city', 'In the countryside', 'By the sea', 'Abroad']],
    /* 65 */ ['type' => 'open',   'q' => 'What makes you proud of us?'],
    /* 66 */ ['type' => 'choice', 'q' => 'Who takes longer to get ready?', 'options' => ['Me', 'You', 'Same', 'Depends on the event']],
    /* 67 */ ['type' => 'choice', 'q' => 'Pick our couple nickname:', 'options' => ['Honey & Bee', 'Salt & Pepper', 'Sun & Moon', 'Peanut Butter & Jelly']],
    /* 68 */ ['type' => 'open',   'q' => "What is one habit of mine you've grown to love?"],
    /* 69 */ ['type' => 'choice', 'q' => 'Best way to end the day?', 'options' => ['A late-night call', 'A sweet voice note', 'Falling asleep on a call', 'A good-night text']],
    /* 70 */ ['type' => 'choice', 'q' => 'Who cries first during a sad movie?', 'options' => ['Me', 'You', 'Both', "We're made of stone 😎"]],
    /* 71 */ ['type' => 'open',   'q' => 'Name three things on your bucket list you would love to do with me.'],
    /* 72 */ ['type' => 'choice', 'q' => 'If our love were a season, it would be…', 'options' => ['Spring — blooming', 'Summer — warm', 'Autumn — cozy', 'Winter — close']],
    /* 73 */ ['type' => 'choice', 'q' => 'Where would you hide a love note for me?', 'options' => ['In my bag', 'Under my pillow', 'In my shoe', 'In my phone case']],
    /* 74 */ ['type' => 'open',   'q' => 'How has being with me changed you?'],
    /* 75 */ ['type' => 'choice', 'q' => 'Most romantic thing to do on a tiny budget?', 'options' => ['A picnic', 'A sunset walk', 'Cooking together', 'Writing letters']],
    /* 76 */ ['type' => 'choice', 'q' => 'Which would you rather do together?', 'options' => ['Skydiving', 'Hot-air balloon ride', 'Scuba diving', 'Nope — a quiet café']],
    /* 77 */ ['type' => 'open',   'q' => 'What do you need more of from me?'],
    /* 78 */ ['type' => 'choice', 'q' => 'How do I look when I am annoyed?', 'options' => ['Adorable', 'Scary', 'Very quiet', 'Dramatic']],
    /* 79 */ ['type' => 'choice', 'q' => 'What is our best team skill?', 'options' => ['Planning', 'Making each other laugh', 'Solving problems', 'Eating a lot']],
    /* 80 */ ['type' => 'open',   'q' => 'Tell me about a moment you felt really proud of me.'],
    /* 81 */ ['type' => 'choice', 'q' => 'Our theme song would be…', 'options' => ['A slow love song', 'Upbeat pop', 'Afrobeat', 'A classic oldie']],
    /* 82 */ ['type' => 'choice', 'q' => 'Who is more likely to get us lost?', 'options' => ['Me', 'You', 'Both — together', 'We never get lost, we explore']],
    /* 83 */ ['type' => 'open',   'q' => "What does 'home' mean to you?"],
    /* 84 */ ['type' => 'choice', 'q' => 'Favorite kind of kiss?', 'options' => ['Good-morning kiss', 'Surprise kiss', 'Goodbye kiss', 'Forehead kiss']],
    /* 85 */ ['type' => 'choice', 'q' => 'If we swapped bodies for a day, what would you do first?', 'options' => ['Check my phone 👀', 'Eat my favorite food', 'Text myself', 'Take a nap']],
    /* 86 */ ['type' => 'open',   'q' => 'What is a tradition you would like us to start?'],
    /* 87 */ ['type' => 'choice', 'q' => 'Who is the better listener?', 'options' => ['Me', 'You', 'Both', 'Depends on the topic']],
    /* 88 */ ['type' => 'choice', 'q' => 'Pick our dream date city:', 'options' => ['Paris', 'Zanzibar', 'Tokyo', 'Cape Town']],
    /* 89 */ ['type' => 'open',   'q' => 'What is something you have always wanted to ask me?'],
    /* 90 */ ['type' => 'choice', 'q' => 'First thing we do if we win the lottery?', 'options' => ['Travel right away', 'Buy a home', 'Help our families', 'Throw a party']],
    /* 91 */ ['type' => 'choice', 'q' => 'What I love most about our talks:', 'options' => ['We laugh a lot', 'We go deep', 'We never run out', 'Our comfortable silences']],
    /* 92 */ ['type' => 'open',   'q' => 'What is the kindest thing someone ever did for you?'],
    /* 93 */ ['type' => 'choice', 'q' => 'Who is the morning person?', 'options' => ['Me', 'You', 'Neither 😴', 'Both, surprisingly']],
    /* 94 */ ['type' => 'choice', 'q' => 'Our couple motto would be:', 'options' => ['Together, always', 'Laugh first', 'Food solves everything', 'You & me vs. the world']],
    /* 95 */ ['type' => 'open',   'q' => 'What is one thing we should always protect in our relationship?'],
    /* 96 */ ['type' => 'choice', 'q' => 'Your favorite place to be with me?', 'options' => ['In your arms', 'On a call', 'Out on a date', 'Anywhere, honestly']],
    /* 97 */ ['type' => 'choice', 'q' => 'After this game, we should…', 'options' => ['Call each other', 'Plan a date', 'Play again', "Say 'I love you' 100 times"]],
    /* 98 */ ['type' => 'open',   'q' => "Finish this sentence: 'I knew you were special when…'"],
    /* 99 */ ['type' => 'open',   'q' => 'What is your wish for us for the next year?'],
    /* 100 */ ['type' => 'open',  'q' => 'Tell me something you want me to remember forever.'],
];
